### ISSUE TITLE
Improper naming 

### ISSUE THREAD

**Issue by jglick** [Azure/azure-artifact-manager-plugin#10]
[This naming](https://github.com/Azure/azure-artifact-manager-plugin/blob/53373e8cb691d47d223b71b8d740d5623c041681/src/main/java/com/microsoft/jenkins/artifactmanager/AzureArtifactManagerFactory.java#L48) inaccurately implies that this is a general-purpose cloud artifact storage plugin. `artifact-manager-s3` uses that label because it defines an extension point allowing jclouds-based implementations, but this plugin does not seem to use that.

**Comment by gavinfish** [comment]
@jglick , so I can use any other naming here right? like `Azure Artifact Storage`.

**Comment by jglick** [comment]
Sure!
